# Wire up travis
language: generic
sudo: true
dist: xenial

branches:
  only:
    - master
    - fork
    - /^test/

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.pyenv_cache

matrix:
  include:
    - env: PYTHON_VERSIONS="3.7.2 3.6.8 3.5.6 2.7.16 3.8-dev pypy2.7-7.0.0 pypy3.6-7.0.0"
    - env: PYTHON_VERSIONS="3.7.2 3.6.8 3.5.6 2.7.16 3.8-dev pypy2.7-7.0.0 pypy3.6-7.0.0"
      os: osx

before_install:
  # for build log timestamps
  - export TZ="America/Chicago"
  - travis_retry wget https://raw.githubusercontent.com/demosdemon/travis-pyenv/81df57d63335e0fd23776e0d5b74873f0f1f13ce/multi-pyenv.sh
  - source multi-pyenv.sh -d
  - pyenv versions

install:
  - travis_retry pip install tox

script:
  - travis_retry tox
