# Wire up travis
language: python
sudo: required
dist: xenial

matrix:
    include:
        - python: 2.7
          env: TOXENV=py27
        - python: 3.5
          env: TOXENV=py35
        - python: 3.6
          env: TOXENV=py36
        - python: 3.7
          env: TOXENV=py37
        - python: 3.8-dev
          env: TOXENV=py38
        - python: pypy
          env: TOXENV=pypy2.7-7.0.0
        - python: pypy3
          env: TOXENV=pypy3.6-7.0.0
        - python: 3.7
          env: TOXENV=docs
        - python: 3.7
          env: TOXENV=lint
        - python: 3.7
          env: TOXENV=py27-cover,py37-cover,coverage
    allow_failures:
        - python: 3.8-dev

cache:
  directories:
    - $HOME/.cache/pip

install:
  - travis_retry pip install tox

script:
  - travis_retry tox
